services:
  nestapp-dev:
    container_name: poker-nestapp-dev
    build:
      context: ./be
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "3101:3000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_NAME=${POSTGRES_NAME:-poker_dev}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres-dev
      - NEST_HOST=0.0.0.0
      - NEST_PORT=3000
      - CLIENT_HOST=${CLIENT_HOST:-0.0.0.0}
      - CLIENT_PORT=${CLIENT_PORT:-8181}
      - PASSPORT_SECRET=${PASSPORT_SECRET}
      - NODE_ENV=development
      - DB_SYNCHRONIZE=true
    env_file:
      - .env.dev
    depends_on:
      postgres-dev:
        condition: service_healthy
    networks:
      - poker-network-dev
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  vueapp-dev:
    container_name: poker-vueapp-dev
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8181:80"
    environment:
      - CADDY_HOST=:80
      - CADDY_BACKEND=poker-nestapp-dev:3000
    env_file:
      - .env.dev
    depends_on:
      nestapp-dev:
        condition: service_healthy
    networks:
      - poker-network-dev
    restart: unless-stopped
    volumes:
      - ./fe/Caddyfile:/etc/caddy/Caddyfile
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:80" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  postgres-dev:
    container_name: poker-postgres-dev
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5535:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_NAME:-poker_dev}
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - poker-network-dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  poker-network-dev:
    driver: bridge

volumes:
  pgdata-dev:
